"""ProfileID Dependence removed

Revision ID: 3729235ae6dd
Revises: 47e90bb3f463
Create Date: 2026-03-26 11:16:53.136444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '3729235ae6dd'
down_revision: Union[str, Sequence[str], None] = '47e90bb3f463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Profile', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'Profile', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Profile', type_='unique')
    op.drop_column('Profile', 'username')
    # ### end Alembic commands ###
