"""Removed LC Entity

Revision ID: 5439e1bdc63d
Revises: cd7f1a1cc5ba
Create Date: 2026-03-18 22:12:02.830101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5439e1bdc63d'
down_revision: Union[str, Sequence[str], None] = 'cd7f1a1cc5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LeetcodeBadges')
    op.drop_table('LeetcodeTags')
    op.drop_table('Leetcode')
    op.drop_index(op.f('ix_APIKeys_key_hash'), table_name='APIKeys')
    op.drop_table('APIKeys')
    op.drop_column('User', 'roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('roles', postgresql.ARRAY(postgresql.ENUM('GLOBAL_ADMIN', 'LOCAL_ADMIN', 'TEAM_LEAD', 'ORGANIZATION_READ', 'PERSONAL_READ', 'PERSONAL_WRITE', 'DEV', name='ROLE')), autoincrement=False, nullable=True))
    op.create_table('APIKeys',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('github_username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('roles', postgresql.ARRAY(postgresql.ENUM('GLOBAL_ADMIN', 'LOCAL_ADMIN', 'TEAM_LEAD', 'ORGANIZATION_READ', 'PERSONAL_READ', 'PERSONAL_WRITE', 'DEV', name='ROLE')), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('APIKeys_pkey'))
    )
    op.create_index(op.f('ix_APIKeys_key_hash'), 'APIKeys', ['key_hash'], unique=True)
    op.create_table('LeetcodeTags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"), autoincrement=False, nullable=False),
    sa.Column('leetcode_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_category', postgresql.ENUM('FUNDAMENTAL', 'INTERMEDIATE', 'ADVANCED', name='LEETCODE_TAG_CATEGORY'), autoincrement=False, nullable=True),
    sa.Column('tag_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('problems_solved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['leetcode_id'], ['Leetcode.id'], name=op.f('LeetcodeTags_leetcode_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Leetcode Tags_pkey'))
    )
    op.create_table('LeetcodeBadges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"), autoincrement=False, nullable=False),
    sa.Column('leetcode_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hover_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['leetcode_id'], ['Leetcode.id'], name=op.f('LeetcodeBadges_leetcode_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Leetcode Badges_pkey'))
    )
    op.create_table('Leetcode',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lc_username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('real_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('about_me', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('school', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('websites', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skill_tags', postgresql.ARRAY(postgresql.ENUM('JAVA', 'C', 'CPP', 'PYTHON', 'CSHARP', 'RUST', 'JAVASCRIPT', 'TYPESCRIPT', 'GO', 'GROOVY', 'RUBY', 'PHP', 'SWIFT', 'REACTJS', 'ANGULARJS', 'NEXTJS', 'VUEJS', 'SVELTE', 'NODEJS', 'DJANGO', 'FLASK', 'SPRINGBOOT', 'GIT', 'MARKDOWN', 'DOCKER', 'KUBERNETES', 'HTML', 'CSS', 'POSTMAN', 'FIREBASE', 'SUPABASE', 'AWS', 'AZURE', 'GCP', 'HEROKU', 'DIGITALOCEAN', 'VERCEL', 'RAILWAY', 'NETLIFY', 'JENKINS', 'REDIS', 'MONGODB', 'MYSQL', 'MSSQL', 'POSTGRESQL', 'SQLITE', 'ELASTICSEARCH', 'KAFKA', 'RABBITMQ', 'GRAPHQL', 'COUCHDB', 'CASSANDRA', name='TOOLS')), autoincrement=False, nullable=True),
    sa.Column('ranking', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reputation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('solution_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_problems_solved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('easy_problems_solved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medium_problems_solved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hard_problems_solved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language_problem_count', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), autoincrement=False, nullable=True),
    sa.Column('attended_contests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('competition_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('global_ranking', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_participants', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('top_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('competition_badge', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['Profile.id'], name=op.f('Leetcode_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Leetcode_pkey'))
    )
    # ### end Alembic commands ###
