"""Mig 1 - 10.02.2025

Revision ID: cd7f1a1cc5ba
Revises: 58d213ac2cce
Create Date: 2026-02-10 14:45:00.155333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7f1a1cc5ba'
down_revision: Union[str, Sequence[str], None] = '58d213ac2cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
