"""Added Auth Mechanism

Revision ID: e9d53ac6b8f8
Revises: cd7f1a1cc5ba
Create Date: 2026-02-25 11:40:01.620436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e9d53ac6b8f8'
down_revision: Union[str, Sequence[str], None] = 'cd7f1a1cc5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('APIKeys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('github_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_in', sa.DateTime(), nullable=True),
    sa.Column('roles', sa.ARRAY(sa.Enum('GLOBAL_ADMIN', 'LOCAL_ADMIN', 'TEAM_LEAD', 'ORGANIZATION_READ', 'PERSONAL_READ', 'PERSONAL_WRITE', 'DEV', name='ROLE')), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_APIKeys_key_hash'), 'APIKeys', ['key_hash'], unique=True)
    op.drop_constraint(op.f('Document_profile_id_fkey'), 'Document', type_='foreignkey')
    op.create_foreign_key(None, 'Document', 'Profile', ['profile_id'], ['id'])
    op.drop_constraint(op.f('Education_profile_id_fkey'), 'Education', type_='foreignkey')
    op.create_foreign_key(None, 'Education', 'Profile', ['profile_id'], ['id'])
    op.drop_constraint(op.f('Links_user_id_fkey'), 'Links', type_='foreignkey')
    op.create_foreign_key(None, 'Links', 'User', ['user_id'], ['id'])
    op.drop_constraint(op.f('Profile_user_id_fkey'), 'Profile', type_='foreignkey')
    op.create_foreign_key(None, 'Profile', 'User', ['user_id'], ['id'])
    op.add_column('User', sa.Column('roles', sa.ARRAY(sa.Enum('GLOBAL_ADMIN', 'LOCAL_ADMIN', 'TEAM_LEAD', 'ORGANIZATION_READ', 'PERSONAL_READ', 'PERSONAL_WRITE', name='ROLE')), nullable=True))
    op.drop_constraint(op.f('WorkExperience_profile_id_fkey'), 'WorkExperience', type_='foreignkey')
    op.create_foreign_key(None, 'WorkExperience', 'Profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'WorkExperience', type_='foreignkey')
    op.create_foreign_key(op.f('WorkExperience_profile_id_fkey'), 'WorkExperience', 'Profile', ['profile_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('User', 'roles')
    op.drop_constraint(None, 'Profile', type_='foreignkey')
    op.create_foreign_key(op.f('Profile_user_id_fkey'), 'Profile', 'User', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'Links', type_='foreignkey')
    op.create_foreign_key(op.f('Links_user_id_fkey'), 'Links', 'User', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'Education', type_='foreignkey')
    op.create_foreign_key(op.f('Education_profile_id_fkey'), 'Education', 'Profile', ['profile_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'Document', type_='foreignkey')
    op.create_foreign_key(op.f('Document_profile_id_fkey'), 'Document', 'Profile', ['profile_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_APIKeys_key_hash'), table_name='APIKeys')
    op.drop_table('APIKeys')
    # ### end Alembic commands ###
