from typing import List, Optional, Union
from datetime import date, datetime
from sqlmodel import SQLModel, Field, Relationship
from enum import Enum
from pydantic import BaseModel
from typing_extensions import Annotated
from uuid import UUID, uuid4

# Enums for USER-DEFINED types
from enum import Enum

# CAUSE
class Cause(str, Enum):
    EDUCATION = "EDUCATION"
    ENVIRONMENT = "ENVIRONMENT"
    SOCIAL_CAUSES = "SOCIAL_CAUSES"
    HUMAN_RIGHT = "HUMAN_RIGHT"
    SCIENCE_TECHNOLOGY = "SCIENCE_TECHNOLOGY"

# CERTIFICATION_TYPE
class CertificationType(str, Enum):
    CERTIFICATE = "CERTIFICATE"
    LICENSE = "LICENSE"
    CERTIFICATION = "CERTIFICATION"

# CURRENCY
class Currency(str, Enum):
    INR = "INR"
    USD = "USD"
    CHF = "CHF"
    EUR = "EUR"
    AUD = "AUD"
    SGD = "SGD"
    GBP = "GBP"

# DIFFICULTY
class Difficulty(str, Enum):
    EASY = "EASY"
    MEDIUM = "MEDIUM"
    HARD = "HARD"
    EXTREME = "EXTREME"

# DOMAIN
class Domain(str, Enum):
    FRONTEND = "FRONTEND"
    BACKEND = "BACKEND"
    FULLSTACK = "FULLSTACK"
    SDE_TEST = "SDE_TEST"
    QUALITY_ASSURANCE = "QUALITY_ASSURANCE"
    TEST_AUTOMATION = "TEST_AUTOMATION"
    DEVOPS = "DEVOPS"
    MLOPS = "MLOPS"
    CI_CD = "CI_CD"
    CLOUD = "CLOUD"
    SITE_RELIABILITY = "SITE_RELIABILITY"
    SOFTWARE_INFRASTRUCTURE = "SOFTWARE_INFRASTRUCTURE"
    DISTRIBUTED_SYSTEMS = "DISTRIBUTED_SYSTEMS"
    EMBEDDED_IOT = "EMBEDDED_IOT"
    ML_ENGINEERING = "ML_ENGINEERING"
    ML_RESEARCH = "ML_RESEARCH"
    DATA_SCIENCE_ANALYSIS = "DATA_SCIENCE_ANALYSIS"
    DATA_ENGINEERING = "DATA_ENGINEERING"
    QUANT_ENGINEERING = "QUANT_ENGINEERING"
    ANDROID = "ANDROID"
    IOS = "IOS"
    CROSS_PLATFORM_MOBILE = "CROSS_PLATFORM_MOBILE"
    WINDOWS = "WINDOWS"
    MACOS = "MACOS"
    LINUX = "LINUX"
    CROSS_PLATFORM_PC = "CROSS_PLATFORM_PC"
    COMPUTER_SYSTEMS = "COMPUTER_SYSTEMS"
    COMPILERS = "COMPILERS"
    GAME_DEV = "GAME_DEV"
    APPLICATION_SECURITY = "APPLICATION_SECURITY"
    PLATFORM_SECURITY = "PLATFORM_SECURITY"
    DEVSECOPS = "DEVSECOPS"
    UI_UX = "UI_UX"
    PRODUCT_MANAGEMENT = "PRODUCT_MANAGEMENT"
    PRODUCT_ENGINEERING = "PRODUCT_ENGINEERING"
    TECHNICAL_WRITING = "TECHNICAL_WRITING"
    OTHER = "OTHER"

# EMPLOYMENT_TYPE
class EmploymentType(str, Enum):
    FULL_TIME = "FULL_TIME"
    PART_TIME = "PART_TIME"
    SELF_EMPLOYED = "SELF_EMPLOYED"
    FREELANCE = "FREELANCE"
    CONTRACT = "CONTRACT"
    INTERNSHIP = "INTERNSHIP"
    APPRENTICESHIP = "APPRENTICESHIP"
    SEASONAL = "SEASONAL"

class SchoolType(str, Enum):
    UNIVERSITY = "UNIVERSITY"
    COLLEGE = "COLLEGE"
    SCHOOL = "SCHOOL"
    OTHER = "OTHER"
    COURSE = "COURSE"
    BOOTCAMP = "BOOTCAMP"

# LEETCODE_TAG_CATEGORY
class LeetcodeTagCategory(str, Enum):
    FUNDAMENTAL = "FUNDAMENTAL"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"

# PROJECT_LEVEL
class ProjectLevel(str, Enum):
    USER_PROJECT = "USER_PROJECT"
    DIJKSTRA_PROJECT = "DIJKSTRA_PROJECT"
    DIJKSTRA_AFFILIATE_PROJECT = "DIJKSTRA_AFFILIATE_PROJECT"
    OS_FRIENDLY_PROJECTS = "OS_FRIENDLY_PROJECTS"
    OS_HARD_PROJECTS = "OS_HARD_PROJECTS"

# RANK
class Rank(str, Enum):
    UNRANKED = "UNRANKED"
    IRON_1 = "IRON_1"
    IRON_2 = "IRON_2"
    IRON_3 = "IRON_3"
    BRONZE_1 = "BRONZE_1"
    BRONZE_2 = "BRONZE_2"
    BRONZE_3 = "BRONZE_3"
    SILVER_1 = "SILVER_1"
    SILVER_2 = "SILVER_2"
    SILVER_3 = "SILVER_3"
    GOLD_1 = "GOLD_1"
    GOLD_2 = "GOLD_2"
    GOLD_3 = "GOLD_3"
    PLATINUM_1 = "PLATINUM_1"
    PLATINUM_2 = "PLATINUM_2"
    PLATINUM_3 = "PLATINUM_3"
    DIAMOND_1 = "DIAMOND_1"
    DIAMOND_2 = "DIAMOND_2"
    DIAMOND_3 = "DIAMOND_3"
    EMERALD_1 = "EMERALD_1"
    EMERALD_2 = "EMERALD_2"
    EMERALD_3 = "EMERALD_3"
    LAPIS_1 = "LAPIS_1"
    LAPIS_2 = "LAPIS_2"
    LAPIS_3 = "LAPIS_3"
    QUARTZ_1 = "QUARTZ_1"
    QUARTZ_2 = "QUARTZ_2"
    QUARTZ_3 = "QUARTZ_3"
    SAPHIRE_1 = "SAPHIRE_1"
    SAPHIRE_2 = "SAPHIRE_2"
    SAPHIRE_3 = "SAPHIRE_3"
    OBSIDIAN = "OBSIDIAN"

# ROLE
class Role(str, Enum):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    TEAM_LEAD = "TEAM_LEAD"

# STATUS
class Status(str, Enum):
    TODO = "TODO"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"
    BACKLOG = "BACKLOG"
    BLOCKED = "BLOCKED"
    OTHER = "OTHER"

# TOOLS
class Tools(str, Enum):
    JAVA = "JAVA"
    C = "C"
    CPP = "CPP"
    PYTHON = "PYTHON"
    CSHARP = "CSHARP"
    RUST = "RUST"
    JAVASCRIPT = "JAVASCRIPT"
    TYPESCRIPT = "TYPESCRIPT"
    GO = "GO"
    GROOVY = "GROOVY"
    RUBY = "RUBY"
    PHP = "PHP"
    SWIFT = "SWIFT"
    REACTJS = "REACTJS"
    ANGULARJS = "ANGULARJS"
    NEXTJS = "NEXTJS"
    VUEJS = "VUEJS"
    SVELTE = "SVELTE"
    NODEJS = "NODEJS"
    DJANGO = "DJANGO"
    FLASK = "FLASK"
    SPRINGBOOT = "SPRINGBOOT"
    GIT = "GIT"
    MARKDOWN = "MARKDOWN"
    DOCKER = "DOCKER"
    KUBERNETES = "KUBERNETES"
    HTML = "HTML"
    CSS = "CSS"
    POSTMAN = "POSTMAN"
    FIREBASE = "FIREBASE"
    SUPABASE = "SUPABASE"
    AWS = "AWS"
    AZURE = "AZURE"
    GCP = "GCP"
    HEROKU = "HEROKU"
    DIGITALOCEAN = "DIGITALOCEAN"
    VERCEL = "VERCEL"
    RAILWAY = "RAILWAY"
    NETLIFY = "NETLIFY"
    JENKINS = "JENKINS"
    REDIS = "REDIS"
    MONGODB = "MONGODB"
    MYSQL = "MYSQL"
    MSSQL = "MSSQL"
    POSTGRESQL = "POSTGRESQL"
    SQLITE = "SQLITE"
    ELASTICSEARCH = "ELASTICSEARCH"
    KAFKA = "KAFKA"
    RABBITMQ = "RABBITMQ"
    GRAPHQL = "GRAPHQL"
    COUCHDB = "COUCHDB"
    CASSANDRA = "CASSANDRA"

# WORK_LOCATION_TYPE
class WorkLocationType(str, Enum):
    ON_SITE = "ON_SITE"
    REMOTE = "REMOTE"
    HYBRID = "HYBRID"

# TEST_SCORE_TYPE
class TestScoreType(str, Enum):
    GRE = "GRE"
    GMAT = "GMAT"
    CGPA = "CGPA"    
    TENTH = "TENTH"
    TWELFTH = "TWELFTH"

# DEGREE
class Degree(str, Enum):
    BTECH = "BTECH"
    BSC = "BSC"
    BE = "BE"
    BCA = "BCA"
    BSCHONS = "BSCHONS"
    BDES = "BDES"
    BPHIL = "BPHIL"
    MTECH = "MTECH"
    MSC = "MSC"
    ME = "ME"
    MCA = "MCA"
    MSR = "MSR"
    MBA = "MBA"
    MDES = "MDES"
    MPHIL = "MPHIL"
    PGDM = "PGDM"
    PHD = "PHD"
    DENG = "DENG"

# SKILL_CATEGORY
class SkillCategory(str, Enum):
    PROGRAMMING_LANGUAGES = "PROGRAMMING_LANGUAGES"
    FRAMEWORKS_AND_LIBRARIES = "FRAMEWORKS_AND_LIBRARIES"
    DATABASES = "DATABASES"
    CLOUD_DEVOPS = "CLOUD_DEVOPS"
    TOOLS_AND_TECHNOLOGIES = "TOOLS_AND_TECHNOLOGIES"
    OTHER = "OTHER"

